version: "3.8"

services:
  app:
    container_name: wellness-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/wellness_db?schema=public
    depends_on:
      - db

  db:
    container_name: wellness-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: wellness_db
    ports:
      - "5434:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: wellness-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
