import { RegionCode } from "@prisma/client";

export const provincesData = [
  // ===== CENTRAL =====
  { code: "BKK", th: "กรุงเทพมหานคร", en: "Bangkok", region: RegionCode.CENTRAL },
  { code: "SPK", th: "สมุทรปราการ", en: "Samut Prakan", region: RegionCode.CENTRAL },
  { code: "NBI", th: "นนทบุรี", en: "Nonthaburi", region: RegionCode.CENTRAL },
  { code: "PTE", th: "ปทุมธานี", en: "Pathum Thani", region: RegionCode.CENTRAL },
  { code: "AYA", th: "พระนครศรีอยุธยา", en: "Ayutthaya", region: RegionCode.CENTRAL },
  { code: "ATG", th: "อ่างทอง", en: "Ang Thong", region: RegionCode.CENTRAL },
  { code: "LBY", th: "ลพบุรี", en: "Lopburi", region: RegionCode.CENTRAL },
  { code: "SBR", th: "สิงห์บุรี", en: "Sing Buri", region: RegionCode.CENTRAL },
  { code: "CNT", th: "ชัยนาท", en: "Chai Nat", region: RegionCode.CENTRAL },
  { code: "SRB", th: "สระบุรี", en: "Saraburi", region: RegionCode.CENTRAL },
  { code: "SPB", th: "สุพรรณบุรี", en: "Suphan Buri", region: RegionCode.CENTRAL },
  { code: "NPT", th: "นครปฐม", en: "Nakhon Pathom", region: RegionCode.CENTRAL },
  { code: "SMK", th: "สมุทรสาคร", en: "Samut Sakhon", region: RegionCode.CENTRAL },
  { code: "SMG", th: "สมุทรสงคราม", en: "Samut Songkhram", region: RegionCode.CENTRAL },
  { code: "PBI", th: "เพชรบุรี", en: "Phetchaburi", region: RegionCode.CENTRAL },
  { code: "PKN", th: "ประจวบคีรีขันธ์", en: "Prachuap Khiri Khan", region: RegionCode.CENTRAL },
  { code: "KCB", th: "กาญจนบุรี", en: "Kanchanaburi", region: RegionCode.CENTRAL },
  { code: "RBR", th: "ราชบุรี", en: "Ratchaburi", region: RegionCode.CENTRAL },

  // ===== EAST =====
  { code: "CBI", th: "ชลบุรี", en: "Chonburi", region: RegionCode.EAST },
  { code: "RYG", th: "ระยอง", en: "Rayong", region: RegionCode.EAST },
  { code: "CTI", th: "จันทบุรี", en: "Chanthaburi", region: RegionCode.EAST },
  { code: "TRT", th: "ตราด", en: "Trat", region: RegionCode.EAST },
  { code: "CCO", th: "ฉะเชิงเทรา", en: "Chachoengsao", region: RegionCode.EAST },
  { code: "PJN", th: "ปราจีนบุรี", en: "Prachinburi", region: RegionCode.EAST },
  { code: "NYK", th: "นครนายก", en: "Nakhon Nayok", region: RegionCode.EAST },
  { code: "SKW", th: "สระแก้ว", en: "Sa Kaeo", region: RegionCode.EAST },

  // ===== NORTHEAST =====
  { code: "NRM", th: "นครราชสีมา", en: "Nakhon Ratchasima", region: RegionCode.NORTHEAST },
  { code: "BRM", th: "บุรีรัมย์", en: "Buriram", region: RegionCode.NORTHEAST },
  { code: "SRN", th: "สุรินทร์", en: "Surin", region: RegionCode.NORTHEAST },
  { code: "SSK", th: "ศรีสะเกษ", en: "Sisaket", region: RegionCode.NORTHEAST },
  { code: "UBN", th: "อุบลราชธานี", en: "Ubon Ratchathani", region: RegionCode.NORTHEAST },
  { code: "YST", th: "ยโสธร", en: "Yasothon", region: RegionCode.NORTHEAST },
  { code: "ACR", th: "อำนาจเจริญ", en: "Amnat Charoen", region: RegionCode.NORTHEAST },
  { code: "BKN", th: "บึงกาฬ", en: "Bueng Kan", region: RegionCode.NORTHEAST },
  { code: "NBL", th: "หนองบัวลำภู", en: "Nong Bua Lamphu", region: RegionCode.NORTHEAST },
  { code: "KKN", th: "ขอนแก่น", en: "Khon Kaen", region: RegionCode.NORTHEAST },
  { code: "UDN", th: "อุดรธานี", en: "Udon Thani", region: RegionCode.NORTHEAST },
  { code: "LEI", th: "เลย", en: "Loei", region: RegionCode.NORTHEAST },
  { code: "NKI", th: "หนองคาย", en: "Nong Khai", region: RegionCode.NORTHEAST },
  { code: "MKM", th: "มหาสารคาม", en: "Maha Sarakham", region: RegionCode.NORTHEAST },
  { code: "RET", th: "ร้อยเอ็ด", en: "Roi Et", region: RegionCode.NORTHEAST },
  { code: "KSN", th: "กาฬสินธุ์", en: "Kalasin", region: RegionCode.NORTHEAST },
  { code: "SNK", th: "สกลนคร", en: "Sakon Nakhon", region: RegionCode.NORTHEAST },
  { code: "NPM", th: "นครพนม", en: "Nakhon Phanom", region: RegionCode.NORTHEAST },
  { code: "MDH", th: "มุกดาหาร", en: "Mukdahan", region: RegionCode.NORTHEAST },

  // ===== NORTH =====
  { code: "CNX", th: "เชียงใหม่", en: "Chiang Mai", region: RegionCode.NORTH },
  { code: "LPN", th: "ลำพูน", en: "Lamphun", region: RegionCode.NORTH },
  { code: "LPG", th: "ลำปาง", en: "Lampang", region: RegionCode.NORTH },
  { code: "UTT", th: "อุตรดิตถ์", en: "Uttaradit", region: RegionCode.NORTH },
  { code: "PRE", th: "แพร่", en: "Phrae", region: RegionCode.NORTH },
  { code: "NAN", th: "น่าน", en: "Nan", region: RegionCode.NORTH },
  { code: "PYO", th: "พะเยา", en: "Phayao", region: RegionCode.NORTH },
  { code: "CRI", th: "เชียงราย", en: "Chiang Rai", region: RegionCode.NORTH },
  { code: "MSN", th: "แม่ฮ่องสอน", en: "Mae Hong Son", region: RegionCode.NORTH },
  { code: "NSN", th: "นครสวรรค์", en: "Nakhon Sawan", region: RegionCode.NORTH },
  { code: "UTI", th: "อุทัยธานี", en: "Uthai Thani", region: RegionCode.NORTH },
  { code: "KPT", th: "กำแพงเพชร", en: "Kamphaeng Phet", region: RegionCode.NORTH },
  { code: "TAK", th: "ตาก", en: "Tak", region: RegionCode.NORTH },
  { code: "STI", th: "สุโขทัย", en: "Sukhothai", region: RegionCode.NORTH },
  { code: "PHS", th: "พิษณุโลก", en: "Phitsanulok", region: RegionCode.NORTH },
  { code: "PCT", th: "พิจิตร", en: "Phichit", region: RegionCode.NORTH },
  { code: "PCB", th: "เพชรบูรณ์", en: "Phetchabun", region: RegionCode.NORTH },

  // ===== SOUTH =====
  { code: "NST", th: "นครศรีธรรมราช", en: "Nakhon Si Thammarat", region: RegionCode.SOUTH },
  { code: "KBI", th: "กระบี่", en: "Krabi", region: RegionCode.SOUTH },
  { code: "PNG", th: "พังงา", en: "Phang Nga", region: RegionCode.SOUTH },
  { code: "PSN", th: "ภูเก็ต", en: "Phuket", region: RegionCode.SOUTH },
  { code: "SRT", th: "สุราษฎร์ธานี", en: "Surat Thani", region: RegionCode.SOUTH },
  { code: "RNG", th: "ระนอง", en: "Ranong", region: RegionCode.SOUTH },
  { code: "CPN", th: "ชุมพร", en: "Chumphon", region: RegionCode.SOUTH },
  { code: "SKA", th: "สงขลา", en: "Songkhla", region: RegionCode.SOUTH },
  { code: "STN", th: "สตูล", en: "Satun", region: RegionCode.SOUTH },
  { code: "TRG", th: "ตรัง", en: "Trang", region: RegionCode.SOUTH },
  { code: "PLG", th: "พัทลุง", en: "Phatthalung", region: RegionCode.SOUTH },
  { code: "PTN", th: "ปัตตานี", en: "Pattani", region: RegionCode.SOUTH },
  { code: "YLA", th: "ยะลา", en: "Yala", region: RegionCode.SOUTH },
  { code: "NWT", th: "นราธิวาส", en: "Narathiwat", region: RegionCode.SOUTH },
] as const;
